### ISSUE TITLE
Build fails at Step 9 for nginx

### ISSUE THREAD

**Issue by kayiwa** [jbfink/docker-atom#1]
running Docker 1.7.0 I run into this error. 

Step 8 : RUN rm /etc/php5/fpm/pool.d/www.conf
 ---> Using cache
 ---> 1815c3b0671f
Step 9 : ADD http://storage.accesstomemory.org/releases/atom-2.1.2.tar.gz /
Service 'nginx' failed to build: Get https://storage.accesstomemory.org/releases/atom-2.1.2.tar.gz: x509: certificate signed by unknown authority

**Comment by jbfink** [comment]
Huh! Trying to do a wget of atom-2.1.2.tar.gz results in the following error:

```
Connecting to storage.accesstomemory.org (storage.accesstomemory.org)|167.114.216.99|:443... connected.
ERROR: cannot verify storage.accesstomemory.org's certificate, issued by ‘CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to storage.accesstomemory.org insecurely, use `--no-check-certificate'.
```

Looks like Artefactual needs to fix their SSL cert. I'll see if there's a way I can disable checks for Docker ADD command in the meantime and see if I can't let Artefactual know about their cert as well. Thanks for letting me know!

**Comment by jbfink** [comment]
Aaaaand SSL is fixed! Or whatever, it's working again. OK!
